import Navbar from "@/pages/shared/Navbar";

export const metadata = {
  title: "Portfolio of Wajed",
  description: "Generated by Nextjs",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Navbar />
      <main className="">{children}</main>
    </div>
  );
}
